version: 0.2

phases:
  build:
    commands:
      - mkdir -p output
      - cp -r app.py connect.py python.py templates static requirement.txt scripts output/
      - chmod +x output/scripts/*.sh

artifacts:
  files:
    - '**/*'
  base-directory: output
